"""
Export investigation as Markdown document.

Generates a structured Markdown report of a troubleshooting investigation
for sharing via Teams, email, or Confluence.

Why export-as-Markdown for Spark/Synapse/Kusto troubleshooting:
- Post-incident reviews (PIRs) require a structured write-up; exporting
  the investigation saves the support engineer from rewriting it
- Teams channel updates need a summary of what was found — Markdown
  renders natively in Teams adaptive cards
- Confluence pages for knowledge base updates can be seeded from the
  export, turning one investigation into reusable documentation
- Audit trails for compliance: having a timestamped Markdown export
  proves what was investigated and when
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from src.models import (
    ConversationContext,
    HistoricalIncident,
    MessageRole,
    ParsedFailure,
)


def export_investigation_markdown(
    alert: ParsedFailure,
    conversation: Optional[ConversationContext] = None,
    similar_incidents: Optional[list[HistoricalIncident]] = None,
    analysis_notes: str = "",
    include_full_chat: bool = True,
) -> str:
    """
    Export a full investigation as a Markdown document.

    Args:
        alert: The primary alert being investigated
        conversation: Chat conversation history
        similar_incidents: Related past incidents
        analysis_notes: Additional notes from the engineer
        include_full_chat: Whether to include full chat transcript

    Returns:
        Formatted Markdown string
    """
    now = datetime.now(timezone.utc)
    lines: list[str] = []

    # Header
    lines.append(f"# Investigation Report: {alert.pipeline_name}")
    lines.append("")
    lines.append(f"**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Alert ID:** {alert.failure_id}")
    lines.append(f"**Severity:** {alert.severity.value.upper()}")
    lines.append(f"**Status:** Under Investigation")
    lines.append("")

    # Alert Summary
    lines.append("## Alert Summary")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Pipeline | {alert.pipeline_name} |")
    lines.append(f"| Error Class | {alert.error_class} |")
    lines.append(f"| Severity | {alert.severity.value.upper()} |")
    lines.append(f"| Source | {alert.source.value} |")
    lines.append(f"| Pipeline Type | {alert.pipeline_type.value} |")
    lines.append(f"| Timestamp | {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')} |")
    lines.append("")

    # Root Cause
    lines.append("## Root Cause Analysis")
    lines.append("")
    if alert.root_cause_summary:
        lines.append(alert.root_cause_summary)
    else:
        lines.append("*Root cause analysis pending.*")
    lines.append("")

    # Error Message
    lines.append("## Error Message")
    lines.append("")
    lines.append("```")
    lines.append(alert.error_message[:2000])
    lines.append("```")
    lines.append("")

    # Log Snippet
    if alert.log_snippet:
        lines.append("## Log Snippet")
        lines.append("")
        lines.append("```")
        lines.append(alert.log_snippet[:3000])
        lines.append("```")
        lines.append("")

    # Similar Incidents
    if similar_incidents:
        lines.append("## Similar Past Incidents")
        lines.append("")
        for inc in similar_incidents[:5]:
            lines.append(f"### {inc.incident_id}: {inc.title}")
            lines.append(f"- **Pipeline:** {inc.pipeline_name}")
            lines.append(f"- **Root Cause:** {inc.root_cause}")
            lines.append(f"- **Resolution:** {inc.resolution}")
            lines.append(f"- **Similarity:** {inc.similarity_score:.0%}")
            lines.append("")

    # Conversation Transcript
    if include_full_chat and conversation and conversation.messages:
        lines.append("## Investigation Chat Transcript")
        lines.append("")
        for msg in conversation.messages:
            role = "**Engineer**" if msg.role == MessageRole.USER else "**Alert Whisperer**"
            timestamp = msg.timestamp.strftime("%H:%M:%S")
            lines.append(f"*[{timestamp}]* {role}:")
            lines.append("")
            lines.append(msg.content)
            lines.append("")
            lines.append("---")
            lines.append("")

    # Additional Notes
    if analysis_notes:
        lines.append("## Additional Notes")
        lines.append("")
        lines.append(analysis_notes)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Report generated by Alert Whisperer at {now.strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines)
